name: $project.name
version: $project.version
main: io.github.blugon0921.playanimation.PlayAnimation
api-version: 1.17
description: PlayAnimation
author: Blugon

commands:
  animation:
    description: Play/Stop Animation
