name: ${project.name}
version: ${project.version}
main: ${project.group}.playanimation.PlayAnimation
api-version: 1.17
description: ${project.name}
author: Blugon

commands:
  animation:
    description: Play/Stop Animation
